# Setup
title:               Bellog
tagline:             
description:         하고 싶은 것만 하며<br> 살 수는 없으니까..
url:                 https://jm991014.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Bellog
  url:               
  email:             jm991014@gmail.com
  contact:
    github:           https://github.com/jm991014
    email:            mailto:jm991014@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y

# webmaster_verifications:
#   google: 2qxjpU93UkaAuZuSLiT7Jzy1MCKngtyQ1VIOzxy1iPM
#   naver: da8073733e6f72202ebec86e12e420ea4d7d59fb