# Setup
title:               Bellog
tagline:             
description:         하고 싶은 것만 하며<br> 살 수는 없으니까..
url:                 https://jm991014.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Bellog
  url:               
  email:             jm991014@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
