# Setup
title:               Bellog
tagline:             
description:         하고 싶은 것만 하며<br> 살 수는 없으니까..
url:                 https://jm991014.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# nav:
#   Home: '/'
#   Archives: '/archives/'
#   Categories: '/categories/'
#   Tags: '/tags/'

# About/contact
author:
  name:              Bellog
  contact:
    github:           https://github.com/jm991014
    email:            mailto:jm991014@gmail.com
    instagram:        https://instagram.com/jong_myoung

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y

webmaster_verifications:
  google: 2qxjpU93UkaAuZuSLiT7Jzy1MCKngtyQ1VIOzxy1iPM

include:
  - _pages